"""Initial migration

Revision ID: 33d7b9c48623
Revises: 
Create Date: 2025-10-24 01:00:28.465421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d7b9c48623'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=100), nullable=False, comment='에이전트 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='에이전트 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='에이전트 설명'),
    sa.Column('agent_type', sa.String(length=50), nullable=False, comment='에이전트 타입'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'ERROR', name='agentstatus'), nullable=False, comment='에이전트 상태'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=False, comment='최대 동시 작업 수'),
    sa.Column('task_timeout_seconds', sa.Integer(), nullable=False, comment='작업 타임아웃(초)'),
    sa.Column('config', sa.Text(), nullable=True, comment='에이전트 설정 (JSON)'),
    sa.Column('host', sa.String(length=255), nullable=True, comment='호스트'),
    sa.Column('port', sa.Integer(), nullable=True, comment='포트'),
    sa.Column('endpoint', sa.String(length=500), nullable=True, comment='엔드포인트'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='에이전트 버전'),
    sa.Column('last_heartbeat', sa.String(length=50), nullable=True, comment='마지막 하트비트'),
    sa.Column('id', sa.Integer(), nullable=False, comment='기본 키'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='생성자'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='수정자'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=100), nullable=False, comment='작업 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='작업 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='작업 설명'),
    sa.Column('task_type', sa.Enum('DATA_PROCESSING', 'API_CALL', 'FILE_OPERATION', 'NOTIFICATION', 'CUSTOM', name='tasktype'), nullable=False, comment='작업 타입'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT', name='taskstatus'), nullable=False, comment='작업 상태'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='우선순위 (1-10)'),
    sa.Column('input_data', sa.Text(), nullable=True, comment='입력 데이터 (JSON)'),
    sa.Column('output_data', sa.Text(), nullable=True, comment='출력 데이터 (JSON)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='시작 시간'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='완료 시간'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True, comment='타임아웃(초)'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='진행률 (0-100)'),
    sa.Column('agent_id', sa.Integer(), nullable=True, comment='에이전트 ID'),
    sa.Column('id', sa.Integer(), nullable=False, comment='기본 키'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='생성자'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###

